### ISSUE TITLE
Workflow doesnt take url into consideration

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [Levi-Lesches/blocking-issues#10] opened 2022-07-19 00:32 UTC
![workflow doesnt work with url](https://user-images.githubusercontent.com/73130443/179639125-5768adaf-9867-47a6-a81d-915afdff8177.PNG)

edit: to be clear im talking about an url from the same repo and not from another repo

**Comment by Levi-Lesches** [comment] 2022-07-19 00:50
This is working as intended. Since cross-repo support is impossible/impractical (https://github.com/Levi-Lesches/blocking-issues/issues/3), I chose to keep the required string as `#XXX`. This 1) forces you to refer to the same repository and 2) makes the comment resistant to changes in the repository/owner name. Allowing a URL implies cross-repo support, and the code will need to check if the repository is not the same and output a new error message users will have to look out for instead of simply not recognizing the URL. 

Closing, but feel free to reopen or continue with more feedback.

**Closed by Levi-Lesches** 2022-07-19 00:50 UTC
